"""
Configuration Schema Reference - Detailed explanation of the JSON configuration structure
"""

# This document outlines the complete standardized JSON configuration schema
# generated by the framework from Informatica XML files.

STANDARDIZED_CONFIG_SCHEMA = {
    "schema": {
        "version": "1.0",  # Configuration schema version
        "name": "string",  # Workflow/Mapping name from XML
        "description": "string",  # Generated description
        "total_fields": "integer",  # Count of fields
        "fields": [
            {
                "field_id": "string",  # Unique field identifier (field_1, field_2, etc.)
                "name": "string",  # Field name from XML
                "datatype": "string",  # Data type (string, integer, decimal, etc.)
                "length": "integer",  # String field length
                "precision": "integer",  # Total digits for numeric fields
                "scale": "integer",  # Decimal places for numeric fields
                "nullable": "boolean",  # Can field be NULL
                "description": "string",  # Field description from XML
                "sample_value": "any"  # Example value for the datatype
            }
        ]
    },
    
    "transformations": {
        "total_transformations": "integer",  # Count of transformations
        "rules": [
            {
                "transformation_id": "string",  # Unique ID
                "name": "string",  # Transformation name
                "type": "string",  # Type: expression, mapping, lookup, etc.
                "expression": "string",  # Transformation logic/expression
                "enabled": "boolean"  # Is transformation active
            }
        ]
    },
    
    "metadata": {
        "source_file": "string",  # Original XML file path
        "workflow_name": "string",  # Workflow name
        "root_tag": "string",  # Root XML tag name
        "generated_at": "string",  # ISO timestamp when generated
        "generator_version": "string"  # Version of generator
    },
    
    "synthetic_data_rules": {
        "description": "string",  # Description of these rules
        "default_row_count": "integer",  # Default rows to generate
        "seed": "integer",  # Random seed for reproducibility
        "field_rules": [
            {
                "field_name": "string",  # Field name
                "datatype": "string",  # Data type
                "nullable": "boolean",  # Can be NULL
                "null_probability": "float",  # Probability of NULL (0.0-1.0)
                "generation_strategy": "string"  # How to generate: random_text, random_integer, etc.
            }
        ]
    }
}

# ============================================================================
# EXAMPLE OUTPUT
# ============================================================================

EXAMPLE_CONFIG = {
    "schema": {
        "version": "1.0",
        "name": "CustomerDataWorkflow",
        "description": "Schema for CustomerDataWorkflow",
        "total_fields": 5,
        "fields": [
            {
                "field_id": "field_1",
                "name": "customer_id",
                "datatype": "biginteger",
                "length": 20,
                "precision": 19,
                "scale": 0,
                "nullable": False,
                "description": "Unique customer identifier",
                "sample_value": 9223372036854775807
            },
            {
                "field_id": "field_2",
                "name": "first_name",
                "datatype": "string",
                "length": 50,
                "precision": 0,
                "scale": 0,
                "nullable": False,
                "description": "Customer first name",
                "sample_value": "sample_text"
            },
            {
                "field_id": "field_3",
                "name": "email",
                "datatype": "string",
                "length": 100,
                "precision": 0,
                "scale": 0,
                "nullable": False,
                "description": "Customer email address",
                "sample_value": "sample_text"
            },
            {
                "field_id": "field_4",
                "name": "account_balance",
                "datatype": "decimal",
                "length": 15,
                "precision": 15,
                "scale": 2,
                "nullable": False,
                "description": "Current account balance",
                "sample_value": 123.45
            },
            {
                "field_id": "field_5",
                "name": "is_active",
                "datatype": "boolean",
                "length": 1,
                "precision": 1,
                "scale": 0,
                "nullable": False,
                "description": "Account active status",
                "sample_value": True
            }
        ]
    },
    
    "transformations": {
        "total_transformations": 2,
        "rules": [
            {
                "transformation_id": "transform_1",
                "name": "calculate_age",
                "type": "expression",
                "expression": "current_date - birth_date",
                "enabled": True
            },
            {
                "transformation_id": "transform_2",
                "name": "validate_email",
                "type": "expression",
                "expression": "email like '%@%.%'",
                "enabled": True
            }
        ]
    },
    
    "metadata": {
        "source_file": "/path/to/customer_workflow.xml",
        "workflow_name": "CustomerDataWorkflow",
        "root_tag": "Workflow",
        "generated_at": "2024-03-26T14:30:00.123456",
        "generator_version": "1.0"
    },
    
    "synthetic_data_rules": {
        "description": "Rules for generating synthetic data",
        "default_row_count": 100,
        "seed": 42,
        "field_rules": [
            {
                "field_name": "customer_id",
                "datatype": "biginteger",
                "nullable": False,
                "null_probability": 0.0,
                "generation_strategy": "random_biginteger"
            },
            {
                "field_name": "first_name",
                "datatype": "string",
                "nullable": False,
                "null_probability": 0.0,
                "generation_strategy": "random_text"
            },
            {
                "field_name": "email",
                "datatype": "string",
                "nullable": False,
                "null_probability": 0.0,
                "generation_strategy": "random_text"
            },
            {
                "field_name": "account_balance",
                "datatype": "decimal",
                "nullable": False,
                "null_probability": 0.0,
                "generation_strategy": "random_decimal"
            },
            {
                "field_name": "is_active",
                "datatype": "boolean",
                "nullable": False,
                "null_probability": 0.0,
                "generation_strategy": "random_boolean"
            }
        ]
    }
}

# ============================================================================
# GENERATION STRATEGIES REFERENCE
# ============================================================================

GENERATION_STRATEGIES = {
    "random_text": "Generate random text using Faker library",
    "random_integer": "Generate random 32-bit integer",
    "random_biginteger": "Generate random 64-bit integer",
    "random_decimal": "Generate decimal with specified precision/scale",
    "random_double": "Generate large floating point number",
    "random_date": "Generate random date (ISO format)",
    "random_timestamp": "Generate random timestamp (ISO format)",
    "random_datetime": "Generate random datetime (ISO format)",
    "random_boolean": "Generate true/false randomly",
    "random_hex": "Generate random hexadecimal string"
}

# ============================================================================
# DATATYPE MAPPINGS
# ============================================================================

DATATYPE_CONFIGURATIONS = {
    "string": {
        "default_length": 50,
        "min_length": 1,
        "max_length": 9999,
        "strategy": "random_text",
        "precision": 0,
        "scale": 0
    },
    "varchar": {
        "default_length": 50,
        "min_length": 1,
        "max_length": 9999,
        "strategy": "random_text",
        "precision": 0,
        "scale": 0
    },
    "integer": {
        "range_min": -2147483648,
        "range_max": 2147483647,
        "strategy": "random_integer",
        "precision": 10,
        "scale": 0
    },
    "biginteger": {
        "range_min": -9223372036854775808,
        "range_max": 9223372036854775807,
        "strategy": "random_biginteger",
        "precision": 19,
        "scale": 0
    },
    "decimal": {
        "default_precision": 10,
        "default_scale": 2,
        "strategy": "random_decimal",
        "supports_precision": True,
        "supports_scale": True
    },
    "double": {
        "range_min": -1e308,
        "range_max": 1e308,
        "strategy": "random_double"
    },
    "date": {
        "format": "YYYY-MM-DD",
        "strategy": "random_date"
    },
    "timestamp": {
        "format": "ISO 8601",
        "strategy": "random_timestamp"
    },
    "boolean": {
        "values": [True, False],
        "strategy": "random_boolean"
    },
    "blob": {
        "representation": "hexadecimal string",
        "strategy": "random_hex"
    }
}

# ============================================================================
# VALIDATION RULES
# ============================================================================

VALIDATION_RULES = {
    "field_id": "Must be unique, format: field_N",
    "name": "Must be non-empty string",
    "datatype": "Must match supported types",
    "length": "Positive integer, max 9999",
    "precision": "Positive integer",
    "scale": "Non-negative integer, <= precision",
    "nullable": "Boolean value",
    "null_probability": "Float between 0.0 and 1.0"
}

# ============================================================================
# EMPTY TEMPLATE FOR CUSTOM CONFIGURATIONS
# ============================================================================

CUSTOM_CONFIG_TEMPLATE = {
    "schema": {
        "version": "1.0",
        "name": "YOUR_WORKFLOW_NAME",
        "description": "Your workflow description",
        "total_fields": 0,
        "fields": []
    },
    "transformations": {
        "total_transformations": 0,
        "rules": []
    },
    "metadata": {
        "source_file": "custom",
        "workflow_name": "YOUR_WORKFLOW_NAME",
        "generated_at": "2024-01-01T00:00:00",
        "generator_version": "1.0"
    },
    "synthetic_data_rules": {
        "description": "Custom rules for synthetic data",
        "default_row_count": 100,
        "seed": 42,
        "field_rules": []
    }
}
